version: '3.4'

services:
  atadosapi:
    image: atadosapi
    build:
      context: Api
      dockerfile: Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5000"]
    ports:
      - 9000:9000
    environment:
      - FLASK_APP=atadosapi/app.py
