version: '3.4'

services:
  api:
    container_name: api
    image: api
    build:
      context: Api/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=atadosapi/app.py
      - FLASK_ENV=production
      - FLASK_SQLALCHEMY_DATABASE_URI=mysql+mysqlconnector://root:root@database:3306/atadosapi
    networks:
      - database-network
    depends_on:
      - database

  database:
    container_name: db
    image: database
    restart: always
    volumes: 
      - ./Database:/docker-entrypoint-initdb.d/:ro

    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    networks:
      - database-network

networks:
  database-network:
    driver: bridge